# Generated by Django 5.0.4 on 2024-06-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='apartments/'),
        ),
    ]
