# Generated by Django 5.0.4 on 2024-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_apartment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='./static/images/home.jpeg', upload_to='apartments/'),
        ),
    ]
